name: Skip Review Action
on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, '#skipreview') && github.actor == 'liorsachakov'
    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
